"""empty message

Revision ID: 8a1cb1355137
Revises: c74e2d8ac0ad
Create Date: 2025-07-23 00:38:04.555951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a1cb1355137'
down_revision: Union[str, Sequence[str], None] = 'c74e2d8ac0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('geo_x', sa.Float(), nullable=False))
    op.add_column('addresses', sa.Column('geo_y', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'geo_y')
    op.drop_column('addresses', 'geo_x')
    # ### end Alembic commands ###
