"""empty message

Revision ID: c74e2d8ac0ad
Revises: 9c30b33f1111
Create Date: 2025-07-23 00:09:57.875550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74e2d8ac0ad'
down_revision: Union[str, Sequence[str], None] = '9c30b33f1111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('addresses', 'street',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.alter_column('addresses', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'street',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
